channels:
    - conda-forge
    - nodefaults

platforms:
    - linux-64

dependencies:
    - sphinx
    - pygments
    - sphinx-autobuild
    - sphinx_rtd_theme
    - docutils
    - pip:
        - readthedocs-sphinx-search
